### ISSUE TITLE
请问 SP2022 发生的 HC 事件的详情

### ISSUE THREAD

**Issue by coolzz27** [wonderwind271/VE401_TA#1]
抱歉打扰。我在另一个 repo 看到
![image](https://github.com/wonderwind271/VE401_TA/assets/59474508/a147729b-3e10-4830-b7d1-f5784928f625)

但是链接中的 circumstance.md 已经被删除，我有点好奇当年发生了什么。如果方便透露的话，非常感谢。附我的 qq: 3225334137

**Comment by wonderwind271** [comment]
Well it seems that the internet has memory even if it's 2 years ago ...

At any rate, no matter how you look at it, it’s not a good memory for anyone involved at that time. If you're really curious to know what happened at that time, you can simply revert to the previous commit of this git repo (I did not do hard revert so the git history is still here).

**Comment by coolzz27** [comment]
> it’s not a good memory for anyone involved at that time

I'm really sorry about that. And thank you for your reply!
